name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: fibonacci test
      id: fibonacci-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: fibonacci test
        setup-command: ''
        command: gradle test
        timeout: 5
        max-score: 100
        # ---
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ASSIGNMENT-TEST_RESULTS: "${{steps.fibonacci-test.outputs.result}}"
      with:
        runners: fibonacci-test